"""add is_active and total_duration_seconds fields to UserSessionActivity model

Revision ID: 8808c23b0026
Revises: 72fa7190fdcd
Create Date: 2025-06-16 08:04:13.317112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8808c23b0026'
down_revision: Union[str, None] = '72fa7190fdcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session_activity', sa.Column('total_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('user_session_activity', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_session_activity', 'is_active')
    op.drop_column('user_session_activity', 'total_duration_seconds')
    # ### end Alembic commands ###
